name: Deployment Workflow
on:
  push:
    branches: [ main ]

jobs: 
  job_one:
    name: Deploy
    runs-on: linux
    steps:
    - name: runnung SSH Commans on feliciascleaners.com
      uses: appleboy/ssh-action@master
      with:
        host: feliciascleaners.com
        username: wrichards
        key: ${{ secrets.FC_CLIENT_SECRET }}
        port: 22
        script: |
          export PATH=~/.asdf/shims/:$PATH
          ./fc_deploy.sh 